import Head from "next/head";
import Footer from "../comps/Footer";
import MainContent from "../comps/MainContent";
import Navbar from "../comps/Navbar";
import styles from "../styles/Home.module.css";

export default function Home({ questionBuilder }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Question Builder | QB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HEADER */}
      <Navbar />
      {/* BODY */}
      <h2
        style={{
          textAlign: "center",
        }}
      >
        Answer this following 10 questions
      </h2>
      <MainContent questionBuilder={questionBuilder} />
      {/* FOOTER */}
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const response = await fetch("http://localhost:8080/questions");
  const data = await response.json();
  console.log(data);

  return {
    props: {
      questionBuilder: data,
    },
  };
};
